1. Buat Tensor dengan Python

In [52]:
import numpy as np

In [61]:
from numpy import array
T = np.array([
    [[[23,50],[7,12]],[[4,3],[4,4]]],
    [[[3,2],[1,2]],[[3,3],[6,5]]]
])

T.shape


(2, 2, 2, 2)

2. Lakukan Perkalian matriks

In [69]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])


print(A)


[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [70]:
print(B)

[[17]
 [22]
 [19]]


In [72]:
C=A*B
print(C)

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


3. Lakukan Transpose, lalu hitung deterimanan dan invers

In [74]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [76]:
# Matriks A di transpose
print(A.transpose())

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [79]:
#Hitung det dari matriks A
from numpy.linalg import det
C = det(A)
print(C)

131344.0000000002


In [81]:
#Cari invers matriks A
from numpy.linalg import inv
D = inv(A)
print(D)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
