Vektor adalah list suatu number

In [3]:
import numpy as np

In [17]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [5]:
vect_a = np.array(a)
vect_b = np.array(b)

In [6]:
vect_a + vect_b

array([ 7,  9, 11, 13, 15])

# Menghitung Norm dengan Numpy

In [7]:
#define vector
d = [6,8]
vect_d = np.array(d)

In [8]:
#menampilkan norm
np.linalg.norm(vect_d, 2) #2: menggunakan Euclidean Distance    kalo 1: menggunakan Manhattan Distance

10.0

# Penjumlahan dan Pengurangan

## Skalar / Bilangan

In [9]:
vect_d + 10

array([16, 18])

## Antar Vector

In [18]:
#Syarat: Jumlah elemen antar vektor harus sama
vect_a = np.array([1,2,3,4])
vect_b = np.array([1,2,3,4,5])

vect_a + vect_b #error karena jumlah elemen di vect_a dan b berbeda

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

# Tensor

tensor adalah generalisasi suatu matriks

Dia bisa matriks 1 D (seperti vector)

3D (seperti cube) atau

0D (satu buah angka)

In [12]:
# Membuat tensor
from numpy import array

T = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[20,21,22],[23,24,25],[26,27,28]]
])
T

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [16]:
T.shape

#Outputnya: (3,3,3) ,artinya Tensor terdiri dari 3 matkriks, 3 baris dan 3 kolom

(3, 3, 3)